services:
  ros-noetic:
    build: .
    container_name: ros_noetic_vnc
    ports:
      - "5900:5900"  # VNC port
      - "8080:8080"  # noVNC web interface
      - "2222:22"    # SSH port
      - "11311:11311"  # ROS master port
      - "11312:11312"  # ROS parameter server
    volumes:
      - ./workspace:/opt/ros_ws/src
      - ./config:/root/.config
      - ./scripts:/opt/scripts
    environment:
      - DISPLAY=:1
      - ROS_MASTER_URI=http://localhost:11311
      - ROS_HOSTNAME=localhost
      - VNC_RESOLUTION=1364x768
      - VNC_COLOR_DEPTH=24
      - VNC_GEOMETRY=1364x768
      - VNC_SCALE=1
      - VNC_SCALE_CURSOR=1
      - VNC_SHARED=true
      - VNC_REPEAT=true
      - VNC_NOCACHE=10
      - VNC_NOCACHE_CR=true
      - VNC_XKB=true
      - VNC_LISTEN=0.0.0.0
      - VNC_NOPW=true
      - VNC_FOREVER=true
      - NOVNC_HEARTBEAT=30
      - NOVNC_WEB=/opt/noVNC
      - NOVNC_LISTEN=8080
      - NOVNC_VNC=localhost:5900
      - XVFB_SCREEN=0
      - XVFB_DEPTH=24
      - XVFB_AC=true
      - XVFB_EXTENSION_GLX=true
      - XVFB_RENDER=true
      - XVFB_NORESET=true
      - FLUXBOX_LOG=/tmp/fluxbox.log
      - SSH_ENABLED=true
      - TMUX_SESSION=ros_session
      - ROS_WORKSPACE=/opt/ros_ws
      - ROS_SOURCE=/opt/ros/noetic/setup.bash
      - ROS_DEVEL_SOURCE=/opt/ros_ws/devel/setup.bash
    networks:
      - ros_network
    privileged: true
    stdin_open: true
    tty: true
    restart: unless-stopped
    command: ["/opt/scripts/startup.sh", "bash"]

networks:
  ros_network:
    driver: bridge 